# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Temp_prj\Python_prj\Img_preprocess\gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(644, 401)
        self.textEdit_log = QtWidgets.QTextEdit(Form)
        self.textEdit_log.setGeometry(QtCore.QRect(20, 280, 411, 101))
        self.textEdit_log.setObjectName("textEdit_log")
        self.pushButton_log_clear = QtWidgets.QPushButton(Form)
        self.pushButton_log_clear.setGeometry(QtCore.QRect(440, 360, 75, 23))
        self.pushButton_log_clear.setObjectName("pushButton_log_clear")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(440, 30, 191, 191))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(20, 20, 121, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_img_width = QtWidgets.QSpinBox(self.widget)
        self.spinBox_img_width.setMinimum(1)
        self.spinBox_img_width.setMaximum(9999)
        self.spinBox_img_width.setProperty("value", 1024)
        self.spinBox_img_width.setObjectName("spinBox_img_width")
        self.horizontalLayout.addWidget(self.spinBox_img_width)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(20, 50, 121, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_img_height = QtWidgets.QSpinBox(self.widget1)
        self.spinBox_img_height.setMinimum(1)
        self.spinBox_img_height.setMaximum(9999)
        self.spinBox_img_height.setProperty("value", 1030)
        self.spinBox_img_height.setObjectName("spinBox_img_height")
        self.horizontalLayout_2.addWidget(self.spinBox_img_height)
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(20, 90, 164, 80))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.doubleSpinBox_integration = QtWidgets.QDoubleSpinBox(self.widget2)
        self.doubleSpinBox_integration.setMaximum(999.99)
        self.doubleSpinBox_integration.setSingleStep(0.5)
        self.doubleSpinBox_integration.setProperty("value", 20.0)
        self.doubleSpinBox_integration.setObjectName("doubleSpinBox_integration")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_integration)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.doubleSpinBox_shift = QtWidgets.QDoubleSpinBox(self.widget2)
        self.doubleSpinBox_shift.setDecimals(4)
        self.doubleSpinBox_shift.setMaximum(999.99)
        self.doubleSpinBox_shift.setSingleStep(0.001)
        self.doubleSpinBox_shift.setProperty("value", 0.0065)
        self.doubleSpinBox_shift.setObjectName("doubleSpinBox_shift")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_shift)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.doubleSpinBox_gain = QtWidgets.QDoubleSpinBox(self.widget2)
        self.doubleSpinBox_gain.setMaximum(999.99)
        self.doubleSpinBox_gain.setSingleStep(0.5)
        self.doubleSpinBox_gain.setProperty("value", 4.2)
        self.doubleSpinBox_gain.setObjectName("doubleSpinBox_gain")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_gain)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 40, 391, 231))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_openIMG_sig = QtWidgets.QPushButton(self.tab)
        self.pushButton_openIMG_sig.setGeometry(QtCore.QRect(30, 30, 81, 23))
        self.pushButton_openIMG_sig.setObjectName("pushButton_openIMG_sig")
        self.pushButton_sub_dark_sig = QtWidgets.QPushButton(self.tab)
        self.pushButton_sub_dark_sig.setGeometry(QtCore.QRect(30, 90, 81, 23))
        self.pushButton_sub_dark_sig.setObjectName("pushButton_sub_dark_sig")
        self.pushButton_dis_smear = QtWidgets.QPushButton(self.tab)
        self.pushButton_dis_smear.setGeometry(QtCore.QRect(140, 90, 81, 23))
        self.pushButton_dis_smear.setObjectName("pushButton_dis_smear")
        self.pushButton_open_dark_sig = QtWidgets.QPushButton(self.tab)
        self.pushButton_open_dark_sig.setGeometry(QtCore.QRect(140, 30, 81, 23))
        self.pushButton_open_dark_sig.setObjectName("pushButton_open_dark_sig")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_log_clear.clicked.connect(Form.click_log_clear)
        self.pushButton_openIMG_sig.clicked.connect(Form.click_openIMG_sig)
        self.pushButton_open_dark_sig.clicked.connect(Form.click_open_dark_sig)
        self.pushButton_sub_dark_sig.clicked.connect(Form.click_sub_dark_sig)
        self.pushButton_dis_smear.clicked.connect(Form.click_dis_smear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DPC图像预处理工具"))
        self.pushButton_log_clear.setText(_translate("Form", "清空"))
        self.groupBox.setTitle(_translate("Form", "图像信息"))
        self.label.setText(_translate("Form", "图像宽度"))
        self.label_2.setText(_translate("Form", "图像高度"))
        self.label_3.setText(_translate("Form", "积分时间/ms"))
        self.label_4.setText(_translate("Form", "行转移时间/ms"))
        self.label_6.setText(_translate("Form", "图像增益/倍"))
        self.pushButton_openIMG_sig.setText(_translate("Form", "打开图像文件"))
        self.pushButton_sub_dark_sig.setText(_translate("Form", "扣本底"))
        self.pushButton_dis_smear.setText(_translate("Form", "扣帧转移"))
        self.pushButton_open_dark_sig.setText(_translate("Form", "打开本底文件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "单通道预处理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "多通道预处理"))

