# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Temp_prj\Python_prj\Img_preprocess\gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(384, 468)
        self.textEdit_log = QtWidgets.QTextEdit(Form)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 360, 361, 91))
        self.textEdit_log.setObjectName("textEdit_log")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 361, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 10, 171, 161))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_openIMG_sig = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_openIMG_sig.setGeometry(QtCore.QRect(40, 100, 80, 23))
        self.pushButton_openIMG_sig.setObjectName("pushButton_openIMG_sig")
        self.pushButton_open_dark_sig = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_open_dark_sig.setGeometry(QtCore.QRect(40, 130, 80, 23))
        self.pushButton_open_dark_sig.setObjectName("pushButton_open_dark_sig")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setGeometry(QtCore.QRect(10, 30, 108, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_img_width = QtWidgets.QSpinBox(self.widget)
        self.spinBox_img_width.setMinimum(1)
        self.spinBox_img_width.setMaximum(9999)
        self.spinBox_img_width.setProperty("value", 1024)
        self.spinBox_img_width.setObjectName("spinBox_img_width")
        self.horizontalLayout.addWidget(self.spinBox_img_width)
        self.widget1 = QtWidgets.QWidget(self.groupBox_4)
        self.widget1.setGeometry(QtCore.QRect(10, 60, 108, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_img_height = QtWidgets.QSpinBox(self.widget1)
        self.spinBox_img_height.setMinimum(1)
        self.spinBox_img_height.setMaximum(9999)
        self.spinBox_img_height.setProperty("value", 1024)
        self.spinBox_img_height.setObjectName("spinBox_img_height")
        self.horizontalLayout_2.addWidget(self.spinBox_img_height)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 190, 171, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_sub_dark_sig = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_sub_dark_sig.setEnabled(False)
        self.pushButton_sub_dark_sig.setGeometry(QtCore.QRect(10, 90, 71, 23))
        self.pushButton_sub_dark_sig.setObjectName("pushButton_sub_dark_sig")
        self.pushButton_dis_smear = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_dis_smear.setEnabled(False)
        self.pushButton_dis_smear.setGeometry(QtCore.QRect(90, 90, 71, 23))
        self.pushButton_dis_smear.setObjectName("pushButton_dis_smear")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 151, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.spinBox_smear_start_line = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_smear_start_line.setEnabled(True)
        self.spinBox_smear_start_line.setMinimum(0)
        self.spinBox_smear_start_line.setMaximum(9999)
        self.spinBox_smear_start_line.setProperty("value", 0)
        self.spinBox_smear_start_line.setObjectName("spinBox_smear_start_line")
        self.horizontalLayout_6.addWidget(self.spinBox_smear_start_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.spinBox_smear_end_line = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_smear_end_line.setEnabled(True)
        self.spinBox_smear_end_line.setMinimum(0)
        self.spinBox_smear_end_line.setMaximum(9999)
        self.spinBox_smear_end_line.setProperty("value", 5)
        self.spinBox_smear_end_line.setObjectName("spinBox_smear_end_line")
        self.horizontalLayout_7.addWidget(self.spinBox_smear_end_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(190, 10, 161, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_1M30dis_smear = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_1M30dis_smear.setGeometry(QtCore.QRect(20, 50, 101, 23))
        self.pushButton_1M30dis_smear.setObjectName("pushButton_1M30dis_smear")
        self.widget2 = QtWidgets.QWidget(self.groupBox_3)
        self.widget2.setGeometry(QtCore.QRect(11, 20, 141, 22))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.doubleSpinBox_integration = QtWidgets.QDoubleSpinBox(self.widget2)
        self.doubleSpinBox_integration.setEnabled(True)
        self.doubleSpinBox_integration.setDecimals(2)
        self.doubleSpinBox_integration.setMaximum(9999.99)
        self.doubleSpinBox_integration.setSingleStep(0.5)
        self.doubleSpinBox_integration.setProperty("value", 500.0)
        self.doubleSpinBox_integration.setObjectName("doubleSpinBox_integration")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_integration)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(190, 100, 161, 181))
        self.groupBox.setObjectName("groupBox")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_11.setObjectName("label_11")
        self.spinBox_cutX = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_cutX.setGeometry(QtCore.QRect(10, 40, 51, 22))
        self.spinBox_cutX.setMaximum(9999)
        self.spinBox_cutX.setProperty("value", 0)
        self.spinBox_cutX.setObjectName("spinBox_cutX")
        self.spinBox_cutY = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_cutY.setGeometry(QtCore.QRect(70, 40, 51, 22))
        self.spinBox_cutY.setMaximum(9999)
        self.spinBox_cutY.setProperty("value", 0)
        self.spinBox_cutY.setObjectName("spinBox_cutY")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_12.setObjectName("label_12")
        self.spinBox_cut_size = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_cut_size.setGeometry(QtCore.QRect(80, 80, 51, 22))
        self.spinBox_cut_size.setMaximum(9999)
        self.spinBox_cut_size.setProperty("value", 500)
        self.spinBox_cut_size.setObjectName("spinBox_cut_size")
        self.pushButton_img_cut = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_img_cut.setGeometry(QtCore.QRect(40, 110, 75, 23))
        self.pushButton_img_cut.setObjectName("pushButton_img_cut")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 191, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_8.setObjectName("label_8")
        self.spinBox_startX_readdn = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_startX_readdn.setGeometry(QtCore.QRect(10, 40, 51, 22))
        self.spinBox_startX_readdn.setMaximum(2000)
        self.spinBox_startX_readdn.setProperty("value", 510)
        self.spinBox_startX_readdn.setObjectName("spinBox_startX_readdn")
        self.spinBox_startY_readdn = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_startY_readdn.setGeometry(QtCore.QRect(70, 40, 51, 22))
        self.spinBox_startY_readdn.setMaximum(2000)
        self.spinBox_startY_readdn.setProperty("value", 510)
        self.spinBox_startY_readdn.setObjectName("spinBox_startY_readdn")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(80, 120, 111, 16))
        self.label_9.setObjectName("label_9")
        self.spinBox_endX_readdn = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_endX_readdn.setGeometry(QtCore.QRect(70, 140, 51, 22))
        self.spinBox_endX_readdn.setMaximum(2000)
        self.spinBox_endX_readdn.setProperty("value", 520)
        self.spinBox_endX_readdn.setObjectName("spinBox_endX_readdn")
        self.spinBox_endY_readdn = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_endY_readdn.setGeometry(QtCore.QRect(130, 140, 51, 22))
        self.spinBox_endY_readdn.setMaximum(2000)
        self.spinBox_endY_readdn.setProperty("value", 520)
        self.spinBox_endY_readdn.setObjectName("spinBox_endY_readdn")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 80, 131, 20))
        self.label_10.setObjectName("label_10")
        self.pushButton_openIMG_readDN = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_openIMG_readDN.setGeometry(QtCore.QRect(90, 190, 89, 23))
        self.pushButton_openIMG_readDN.setObjectName("pushButton_openIMG_readDN")
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_log_clear = QtWidgets.QPushButton(Form)
        self.pushButton_log_clear.setGeometry(QtCore.QRect(280, 320, 75, 23))
        self.pushButton_log_clear.setObjectName("pushButton_log_clear")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_log_clear.clicked.connect(Form.click_log_clear)
        self.pushButton_openIMG_sig.clicked.connect(Form.click_openIMG_sig)
        self.pushButton_open_dark_sig.clicked.connect(Form.click_open_dark_sig)
        self.pushButton_sub_dark_sig.clicked.connect(Form.click_sub_dark_sig)
        self.pushButton_dis_smear.clicked.connect(Form.click_dis_smear)
        self.pushButton_openIMG_readDN.clicked.connect(Form.click_openIMG_readDN)
        self.pushButton_1M30dis_smear.clicked.connect(Form.click_1M30dis_smear)
        self.pushButton_img_cut.clicked.connect(Form.click_img_cut)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DPC图像预处理工具"))
        self.groupBox_4.setTitle(_translate("Form", "打开图像"))
        self.pushButton_openIMG_sig.setText(_translate("Form", "打开图像文件"))
        self.pushButton_open_dark_sig.setText(_translate("Form", "打开本底文件"))
        self.label.setText(_translate("Form", "图像宽度"))
        self.label_2.setText(_translate("Form", "图像高度"))
        self.groupBox_5.setTitle(_translate("Form", "DPC图像预处理"))
        self.pushButton_sub_dark_sig.setText(_translate("Form", "扣本底"))
        self.pushButton_dis_smear.setText(_translate("Form", "校正帧转移"))
        self.label_5.setText(_translate("Form", "帧转移起始行"))
        self.label_7.setText(_translate("Form", "帧转移结束行"))
        self.groupBox_3.setTitle(_translate("Form", "1M30相机预处理"))
        self.pushButton_1M30dis_smear.setText(_translate("Form", "扣本底除帧转移"))
        self.label_3.setText(_translate("Form", "积分时间/ms"))
        self.groupBox.setTitle(_translate("Form", "图像裁剪"))
        self.label_11.setText(_translate("Form", "起点坐标（左上角） "))
        self.label_12.setText(_translate("Form", "裁剪后尺寸"))
        self.pushButton_img_cut.setText(_translate("Form", "裁剪"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "单通道预处理"))
        self.groupBox_2.setTitle(_translate("Form", "图像区域选择"))
        self.label_8.setText(_translate("Form", "起点坐标（左上角） "))
        self.label_9.setText(_translate("Form", "终点坐标（右下角）"))
        self.label_10.setText(_translate("Form", "X和Y与S3软件定义一致"))
        self.pushButton_openIMG_readDN.setText(_translate("Form", "打开图像文件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "速读图像DN值"))
        self.pushButton_log_clear.setText(_translate("Form", "清空"))

