# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Temp_prj\Python_prj\Img_preprocess\gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(442, 401)
        self.textEdit_log = QtWidgets.QTextEdit(Form)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 290, 411, 91))
        self.textEdit_log.setObjectName("textEdit_log")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 221, 271))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 91, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_openIMG_sig = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_openIMG_sig.setObjectName("pushButton_openIMG_sig")
        self.verticalLayout_3.addWidget(self.pushButton_openIMG_sig)
        self.pushButton_open_dark_sig = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_open_dark_sig.setObjectName("pushButton_open_dark_sig")
        self.verticalLayout_3.addWidget(self.pushButton_open_dark_sig)
        self.pushButton_sub_dark_sig = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_sub_dark_sig.setEnabled(False)
        self.pushButton_sub_dark_sig.setObjectName("pushButton_sub_dark_sig")
        self.verticalLayout_3.addWidget(self.pushButton_sub_dark_sig)
        self.pushButton_dis_smear = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_dis_smear.setEnabled(False)
        self.pushButton_dis_smear.setObjectName("pushButton_dis_smear")
        self.verticalLayout_3.addWidget(self.pushButton_dis_smear)
        self.pushButton_1M30dis_smear = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_1M30dis_smear.setObjectName("pushButton_1M30dis_smear")
        self.verticalLayout_3.addWidget(self.pushButton_1M30dis_smear)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 191, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_8.setObjectName("label_8")
        self.spinBox_startX_readdn = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_startX_readdn.setGeometry(QtCore.QRect(10, 40, 51, 22))
        self.spinBox_startX_readdn.setMaximum(2000)
        self.spinBox_startX_readdn.setProperty("value", 510)
        self.spinBox_startX_readdn.setObjectName("spinBox_startX_readdn")
        self.spinBox_startY_readdn = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_startY_readdn.setGeometry(QtCore.QRect(70, 40, 51, 22))
        self.spinBox_startY_readdn.setMaximum(2000)
        self.spinBox_startY_readdn.setProperty("value", 510)
        self.spinBox_startY_readdn.setObjectName("spinBox_startY_readdn")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(80, 120, 111, 16))
        self.label_9.setObjectName("label_9")
        self.spinBox_endX_readdn = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_endX_readdn.setGeometry(QtCore.QRect(70, 140, 51, 22))
        self.spinBox_endX_readdn.setMaximum(2000)
        self.spinBox_endX_readdn.setProperty("value", 520)
        self.spinBox_endX_readdn.setObjectName("spinBox_endX_readdn")
        self.spinBox_endY_readdn = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_endY_readdn.setGeometry(QtCore.QRect(130, 140, 51, 22))
        self.spinBox_endY_readdn.setMaximum(2000)
        self.spinBox_endY_readdn.setProperty("value", 520)
        self.spinBox_endY_readdn.setObjectName("spinBox_endY_readdn")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 80, 131, 20))
        self.label_10.setObjectName("label_10")
        self.pushButton_openIMG_readDN = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_openIMG_readDN.setGeometry(QtCore.QRect(90, 190, 89, 23))
        self.pushButton_openIMG_readDN.setObjectName("pushButton_openIMG_readDN")
        self.tabWidget.addTab(self.tab_2, "")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(240, 20, 191, 231))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 121, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_img_width = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_img_width.setMinimum(1)
        self.spinBox_img_width.setMaximum(9999)
        self.spinBox_img_width.setProperty("value", 1024)
        self.spinBox_img_width.setObjectName("spinBox_img_width")
        self.horizontalLayout.addWidget(self.spinBox_img_width)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 50, 121, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_img_height = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBox_img_height.setMinimum(1)
        self.spinBox_img_height.setMaximum(9999)
        self.spinBox_img_height.setProperty("value", 1030)
        self.spinBox_img_height.setObjectName("spinBox_img_height")
        self.horizontalLayout_2.addWidget(self.spinBox_img_height)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 80, 164, 80))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.doubleSpinBox_integration = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.doubleSpinBox_integration.setEnabled(True)
        self.doubleSpinBox_integration.setMaximum(999.99)
        self.doubleSpinBox_integration.setSingleStep(0.5)
        self.doubleSpinBox_integration.setProperty("value", 20.0)
        self.doubleSpinBox_integration.setObjectName("doubleSpinBox_integration")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_integration)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.doubleSpinBox_shift = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.doubleSpinBox_shift.setEnabled(False)
        self.doubleSpinBox_shift.setDecimals(4)
        self.doubleSpinBox_shift.setMaximum(999.99)
        self.doubleSpinBox_shift.setSingleStep(0.001)
        self.doubleSpinBox_shift.setProperty("value", 0.0)
        self.doubleSpinBox_shift.setObjectName("doubleSpinBox_shift")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_shift)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.doubleSpinBox_gain = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.doubleSpinBox_gain.setEnabled(False)
        self.doubleSpinBox_gain.setMaximum(999.99)
        self.doubleSpinBox_gain.setSingleStep(0.5)
        self.doubleSpinBox_gain.setProperty("value", 4.2)
        self.doubleSpinBox_gain.setObjectName("doubleSpinBox_gain")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_gain)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 170, 161, 52))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.spinBox_smear_start_line = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_smear_start_line.setEnabled(True)
        self.spinBox_smear_start_line.setMinimum(0)
        self.spinBox_smear_start_line.setMaximum(9999)
        self.spinBox_smear_start_line.setProperty("value", 0)
        self.spinBox_smear_start_line.setObjectName("spinBox_smear_start_line")
        self.horizontalLayout_6.addWidget(self.spinBox_smear_start_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.spinBox_smear_end_line = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_smear_end_line.setEnabled(True)
        self.spinBox_smear_end_line.setMinimum(0)
        self.spinBox_smear_end_line.setMaximum(9999)
        self.spinBox_smear_end_line.setProperty("value", 5)
        self.spinBox_smear_end_line.setObjectName("spinBox_smear_end_line")
        self.horizontalLayout_7.addWidget(self.spinBox_smear_end_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.pushButton_log_clear = QtWidgets.QPushButton(Form)
        self.pushButton_log_clear.setGeometry(QtCore.QRect(350, 260, 75, 23))
        self.pushButton_log_clear.setObjectName("pushButton_log_clear")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_log_clear.clicked.connect(Form.click_log_clear)
        self.pushButton_openIMG_sig.clicked.connect(Form.click_openIMG_sig)
        self.pushButton_open_dark_sig.clicked.connect(Form.click_open_dark_sig)
        self.pushButton_sub_dark_sig.clicked.connect(Form.click_sub_dark_sig)
        self.pushButton_dis_smear.clicked.connect(Form.click_dis_smear)
        self.pushButton_openIMG_readDN.clicked.connect(Form.click_openIMG_readDN)
        self.pushButton_1M30dis_smear.clicked.connect(Form.click_1M30dis_smear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DPC图像预处理工具"))
        self.pushButton_openIMG_sig.setText(_translate("Form", "打开图像文件"))
        self.pushButton_open_dark_sig.setText(_translate("Form", "打开本底文件"))
        self.pushButton_sub_dark_sig.setText(_translate("Form", "扣本底"))
        self.pushButton_dis_smear.setText(_translate("Form", "校正帧转移"))
        self.pushButton_1M30dis_smear.setText(_translate("Form", "1M30除帧转移"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "单通道预处理"))
        self.groupBox_2.setTitle(_translate("Form", "图像区域选择"))
        self.label_8.setText(_translate("Form", "起点坐标（左上角） "))
        self.label_9.setText(_translate("Form", "终点坐标（右下角）"))
        self.label_10.setText(_translate("Form", "X和Y与S3软件定义一致"))
        self.pushButton_openIMG_readDN.setText(_translate("Form", "打开图像文件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "速读图像DN值"))
        self.groupBox.setTitle(_translate("Form", "图像信息"))
        self.label.setText(_translate("Form", "图像宽度"))
        self.label_2.setText(_translate("Form", "图像高度"))
        self.label_3.setText(_translate("Form", "积分时间/ms"))
        self.label_4.setText(_translate("Form", "预留参数"))
        self.label_6.setText(_translate("Form", "图像增益/倍"))
        self.label_5.setText(_translate("Form", "帧转移起始行"))
        self.label_7.setText(_translate("Form", "帧转移结束行"))
        self.pushButton_log_clear.setText(_translate("Form", "清空"))

